CREATE USER cutbray WITH PASSWORD 'moncos214';

ALTER USER cutbray WITH SUPERUSER;
ALTER USER cutbray WITH CREATEDB;
CREATE DATABASE pppk_exam ;

GRANT ALL PRIVILEGES ON DATABASE pppk_exam TO cutbray;